services:
  bucket:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./bucket:/data
    env_file:
      - .env.bucket.local
    command: server /data --console-address ":9001"
    restart: always
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env.db.local
    volumes:
      - ./pgdata:/data
    restart: always