version: '3.8'
services:
  bucket:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./bucket:/data
    env_file:
      - .env.bucket.local
    command: server /data --console-address ":9001"
